import * as fs from 'node:fs';
import * as path from 'node:path';
import YAML from 'yaml';
import type { LockFile } from '@skillspace/schema';
import { validateLockFile } from '@skillspace/schema';

// ---------------------------------------------------------------------------
// Lock file management (skillspace.lock)
// ---------------------------------------------------------------------------

const LOCK_FILE_NAME = 'skillspace.lock';

/**
 * Read and parse the lock file from a directory.
 */
export function readLockFile(dir: string): LockFile | null {
  const lockPath = path.join(dir, LOCK_FILE_NAME);
  if (!fs.existsSync(lockPath)) {
    return null;
  }

  const raw = fs.readFileSync(lockPath, 'utf-8');
  const parsed = YAML.parse(raw);
  const result = validateLockFile(parsed);

  if (!result.success) {
    throw new Error(`Invalid lock file at ${lockPath}: ${result.errors.message}`);
  }

  return result.data;
}

/**
 * Write a lock file to a directory.
 * Lock files are deterministic — same input produces same output.
 */
export function writeLockFile(dir: string, lock: LockFile): void {
  const lockPath = path.join(dir, LOCK_FILE_NAME);

  // Sort entries for deterministic output
  const sortedLock: LockFile = {
    version: lock.version,
    generated: new Date().toISOString(),
    skills: sortRecord(lock.skills),
    agents: sortRecord(lock.agents),
    mcp_servers: sortRecord(lock.mcp_servers),
  };

  const header = '# DO NOT EDIT MANUALLY — generated by skillspace install\n';
  const content = header + YAML.stringify(sortedLock);

  fs.writeFileSync(lockPath, content, 'utf-8');
}

/**
 * Create an empty lock file.
 */
export function createEmptyLockFile(): LockFile {
  return {
    version: 1,
    generated: new Date().toISOString(),
    skills: {},
    agents: {},
    mcp_servers: {},
  };
}

/**
 * Add a skill entry to a lock file.
 */
export function addSkillToLockFile(
  lock: LockFile,
  name: string,
  entry: {
    version: string;
    resolved: string;
    checksum: string;
    dependencies?: Record<string, string>;
  },
): LockFile {
  return {
    ...lock,
    skills: {
      ...lock.skills,
      [name]: entry,
    },
  };
}

/**
 * Remove a skill entry from a lock file.
 */
export function removeSkillFromLockFile(lock: LockFile, name: string): LockFile {
  const { [name]: _removed, ...remaining } = lock.skills;
  return {
    ...lock,
    skills: remaining,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sortRecord<T>(record: Record<string, T>): Record<string, T> {
  const sorted: Record<string, T> = {};
  for (const key of Object.keys(record).sort()) {
    sorted[key] = record[key]!;
  }
  return sorted;
}
